"""empty message

Revision ID: 557943c650be
Revises: c09f68594638
Create Date: 2025-08-05 14:52:15.572044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '557943c650be'
down_revision = 'c09f68594638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_locked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_locked')

    # ### end Alembic commands ###
