"""Added is_active column to users

Revision ID: 694b751bd525
Revises: bf182866ea74
Create Date: 2025-09-04 11:52:04.685175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '694b751bd525'
down_revision = 'bf182866ea74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
